//! Render the differential matrix three ways — **one row per tool, one column
//! per test** — a wide table plus a prose "divergences worth knowing" section:
//! a Markdown document ([`render`]), a transposed CSV ([`render_csv`]), and a
//! self-contained, well-readable HTML report ([`render_html`]). The HTML report
//! entity-encodes every untrusted cell (`h`/`hc`) so a corrupted cookie's
//! `<script>` or markup renders as text and can never become live HTML. Two reference rows
//! frame the user's question — **RFC** (the *standard*, hand-authored where 6265
//! is prescriptive) and **consensus** (the *expectation*, the modal outcome of
//! the real-world parsers). kekse's deviations are surfaced, not hidden.

use std::borrow::Cow;
use std::collections::BTreeMap;
use std::fmt::Write as _;

use crate::differential::result::ParseOutcome;
use crate::scenario::Scenario;
use crate::taxonomy::Direction;

// ── shared authored narrative ─────────────────────────────────────────────────
// The report's prose lives here once, so the Markdown and HTML renderers cannot
// drift apart. It is authored Markdown (inline `code` spans, **bold**, *italic*):
// `render` emits it verbatim; `render_html` runs it through `md_inline`, which
// renders those inline spans as HTML and escapes everything else.

/// The report title (`#` heading in Markdown, `<h1>` in HTML).
const TITLE: &str = "keksbruch — parser divergence matrix";

/// One-line framing plus the command that regenerates the matrix.
const INTRO: &str =
    "How cookie parsers across languages handle the same difficult and malformed wire — surfacing where implementations diverge. \
     Generated by `cargo test -p keksbruch --features differential -- --ignored`.";

/// The cell vocabulary, as `(symbol, meaning)` rows — rendered as a table (Markdown
/// in [`render`], HTML in [`render_html`]) so the key is scannable rather than a run-on
/// sentence. Meanings are authored inline Markdown (the `code` spans render in both).
const LEGEND_ROWS: &[(&str, &str)] = &[
    (
        "[n=v, …]",
        "a request `Cookie:` header parsed into these name=value pairs, in order",
    ),
    ("∅", "parsed successfully, but into zero cookies"),
    (
        "name=value ;Attr;…",
        "a `Set-Cookie` parsed into one cookie, with its attributes after the `;`",
    ),
    (
        "❌",
        "the parser rejected the whole header or cookie (fail-hard)",
    ),
    (
        "n/a",
        "the parser does not handle this direction (e.g. a request-only library asked to parse a `Set-Cookie`)",
    ),
    (
        "SKIP",
        "the parser or its toolchain was unavailable in this run",
    ),
    (
        "☠️",
        "the parser **crashed** on this payload — an in-process panic, or a sidecar killed by a signal, a non-zero exit, or a hang",
    ),
    ("≡", "a proxy (nginx) forwarded the cookie byte-for-byte"),
    (
        "≠ …",
        "a proxy forwarded the cookie but altered the bytes (the altered value follows)",
    ),
    (
        "⟨array⟩ / ⟨object⟩",
        "the value was parsed as a non-string type — PHP's `$_COOKIE` arrays/maps — shown by type name",
    ),
];

/// The footnote under the legend table (authored inline Markdown).
const LEGEND_NOTE: &str =
    "A **bold** cell differs from the real-world *consensus* — the modal outcome of the other \
     parsers. kekse is the subject under test, so it is excluded from the consensus vote.";

/// The explanatory paragraphs, in order.
const NARRATIVE: [&str; 5] = [
    "The matrix is split by direction into two tables: the **request** `Cookie:` parsers and the \
     **response** `Set-Cookie:` parsers, each listing only the tools that engage that direction \
     (so neither is a wall of `n/a`). Date/expiry behaviour — what a *client* cares about — lives \
     in the Set-Cookie section, where `Expires` is meaningful; the request side carries none.",
    "Request side: the `cookie` crate runs in percent-decoding (`*_encoded`) mode so its values \
     are comparable to kekse's. biscotti is fail-hard and exposes no general iterator, so its \
     accepted pairs are enumerated by name. PHP's `$_COOKIE` is parsed natively behind its \
     built-in server (`php -S`), showing PHP's own quirks — value urldecoding, cookie-name \
     mangling, and transport-layer rejection of CR/LF/NUL. A bracketed name (`name[]`/`name[k]`) \
     makes PHP build an array/map — the only non-string types here, shown by type name \
     (`⟨array⟩`/`⟨object⟩`); every other parser keeps a bracketed name a flat string or drops it. \
     Go (`net/http`, since 1.23) and .NET (`Microsoft.Net.Http.Headers`) parse both directions; a \
     toolchain absent from the run shows `SKIP` (the CI matrix job has them all).",
    "nginx is exercised behind a real openresty server, replayed over a socket like PHP. Its \
     `$cookie_<name>` column is nginx's *native* by-name lookup; `lua-resty-cookie` is an \
     OpenResty Lua library that parses the raw header. `nginx/proxy` is a fidelity axis — did a \
     `proxy_pass` forward the request Cookie verbatim (`≡`), alter it (`≠`), or refuse it (`❌`) — \
     and `nginx/proxy (Set-Cookie)` asks the same of an upstream `Set-Cookie` forwarded back to a \
     client (nginx exposes no *parsed* Set-Cookie to Lua, so it is fidelity, not a parse — it \
     escapes a smuggled CR/LF to `%0D%0A` rather than dropping it). Both are off the consensus vote.",
    "The Java sidecar runs from a JVM image and adds six columns. Two Tomcat request-cookie \
     processors — `Tomcat RFC6265` (strict) and `Tomcat legacy` (lenient) — and the \
     `jakarta.ws.rs` cookie API via two providers (RESTEasy + Jersey), which parse both \
     directions. For Set-Cookie it also runs the JDK's `java.net.HttpCookie` and `Apache \
     HttpClient5`'s RFC 6265 spec — the realistic redistributable stand-in for the proprietary \
     BurpSuite parser, which cannot be bundled or run headless.",
    "Set-Cookie side: alongside the pure parsers (kekse, the `cookie` crate, tough-cookie, \
     SimpleCookie, mitmproxy, Go, .NET, the Java columns) sit the real C HTTP clients. \
     `c/libcurl` drives libcurl's cookie engine offline in C — it cannot export a cookie injected \
     without a `Domain`, so host-only cookies show `❌`; `client/curl` and `client/wget` fetch \
     from a loopback server, the *transfer* view, where the request host supplies the domain (so \
     host-only cookies parse, while a `Domain=` mismatching 127.0.0.1 is refused) — the two views \
     are complementary. A parser that *crashes* on a payload — a panic, a signal, a hang — is \
     marked `☠️` and pinned to that exact payload, distinct from a clean rejection (`❌`) or an \
     unavailable tool (`SKIP`). Rows are tools, columns are tests; the `payload` row is the exact \
     wire (non-displayable bytes shown `\\0` `\\r` `\\n` `\\xNN`). The same matrix is written \
     beside this file as `COOKIE_MATRIX.csv`.",
];

/// The HTML report's stylesheet, inlined so the page is fully self-contained (no
/// CDN/fonts — it must render offline and as a static GitHub Pages file). The
/// wide table scrolls horizontally inside `.matrix-scroll`; its header row and
/// first column stick so a tool/test stays identifiable across ~60 columns.
const CSS: &str = r#":root{--fg:#1f2933;--muted:#9aa5b1;--line:#e1e6eb;--head:#1f2933;--head-fg:#f5f7fa;--rowhead:#f4f6f9;--ref:#eaf1f8;--diverge:#fff3bf;--accent:#1565c0}
*{box-sizing:border-box}
body{margin:0;padding:0 0 4rem;font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--fg);background:#fff}
h1,h2,.intro,.downloads,.prose,ul{padding-left:1.5rem;padding-right:1.5rem}
h1{margin:1.6rem 0 .3rem;font-size:1.55rem}
h2{margin:2.2rem 0 .6rem;font-size:1.2rem}
p{margin:.55rem 0}
.prose{color:#3e4c59}
a{color:var(--accent);text-decoration:none}a:hover{text-decoration:underline}
code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.85em}
.legend-table{margin:.6rem 1.5rem 1.2rem;font-size:13px;border-top:1px solid var(--line);border-left:1px solid var(--line)}
.legend-table td:last-child{white-space:normal}
.matrix-scroll{overflow-x:auto;margin:1.3rem 0;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}
table{border-collapse:separate;border-spacing:0;font-size:12.5px}
th,td{border-right:1px solid var(--line);border-bottom:1px solid var(--line);padding:.32rem .55rem;text-align:left;white-space:nowrap;vertical-align:top}
thead th{position:sticky;top:0;z-index:2;background:var(--head);color:var(--head-fg);font-weight:600}
th:first-child,td:first-child{position:sticky;left:0;z-index:1;background:var(--rowhead);font-weight:600;border-right:2px solid var(--line)}
thead th:first-child{z-index:3}
tr.ref td,tr.ref th:first-child{background:var(--ref)}
td.diverge{background:var(--diverge);font-weight:700}
td.reject{color:#c92a2a}
td.muted{color:var(--muted)}
td.crash{color:#c92a2a;font-weight:700;text-decoration:underline}"#;

/// One matrix column: a parser, with one [`ParseOutcome`] per scenario (aligned
/// to the scenario order).
pub struct Column {
    pub lang: String,
    pub dep: String,
    pub cells: Vec<ParseOutcome>,
}

impl Column {
    fn header(&self) -> String {
        format!("{}/{}", self.lang, self.dep)
    }

    /// kekse is the *subject* under test, excluded from the consensus vote so
    /// we can judge it against the rest of the field.
    fn is_subject(&self) -> bool {
        self.dep.starts_with("kekse")
    }
}

/// The RFC-6265-prescribed verdict, given only where the standard is clear.
/// `None` renders as `—` (the RFC is silent or implementation-defined here).
fn rfc_verdict(id: &str) -> Option<&'static str> {
    match id {
        "delim-semicolon" => Some("`;` splits → 2 pairs"),
        "empty-value" => Some("empty value is valid"),
        "dup-name" => Some("all duplicates kept"),
        "no-equals" | "empty-name" => Some("skip bad pair, keep rest"),
        "extra-equals" => Some("split on first `=`"),
        "markup-no-equals" | "equals-bare" | "equals-double" => Some("skip bad pair, keep rest"),
        "array-name"
        | "assoc-name"
        | "markup-name"
        | "nul-empty-name"
        | "resp-array-name"
        | "resp-quoted-pair-flag" => Some("non-token name skipped"),
        "bracket-value" | "resp-bracket-value" => Some("`[` `]` are cookie-octets"),
        "json-value" | "resp-json-value" => Some("DQUOTE is not a cookie-octet"),
        "attr-unknown" | "attr-bad-maxage" | "attr-garbage-samesite" => {
            Some("keep cookie, ignore attr (§5.2)")
        }
        "attr-duplicate" => Some("keep cookie, last wins (§5.2)"),
        "resp-crlf" => Some("CR/LF must not be smuggled"),
        "resp-ws-surrounding" => Some("trim leading/trailing WSP"),
        "resp-empty-value" => Some("empty value is valid"),
        "resp-ctl-nul" | "resp-ctl-other" => Some("CTL is not a cookie-octet"),
        "resp-quote-interior" => Some("DQUOTE is not a cookie-octet"),
        "resp-non-ascii" => Some("non-ASCII is not a cookie-octet"),
        _ => None,
    }
}

/// The modal outcome across the non-subject, applicable columns — the empirical
/// "expectation". `None` if every real-world parser was n/a or skipped.
fn consensus(row: usize, columns: &[Column]) -> Option<String> {
    let mut votes: BTreeMap<String, usize> = BTreeMap::new();
    for column in columns {
        if column.is_subject() {
            continue;
        }
        match &column.cells[row] {
            // n/a and SKIP never vote; nor do the proxy *forwarding* verdicts —
            // they measure transit fidelity, a different axis than parsing, so
            // they must not sway (or read as) the parse consensus. A crash (an
            // in-process panic or a sidecar that died) is not a parse opinion
            // either — it is excluded so `☠️` never groups into the consensus.
            ParseOutcome::NotApplicable
            | ParseOutcome::Skipped
            | ParseOutcome::Panicked { .. }
            | ParseOutcome::Crashed { .. }
            | ParseOutcome::ForwardedVerbatim
            | ParseOutcome::ForwardedAltered { .. }
            | ParseOutcome::ForwardedRejected => continue,
            other => *votes.entry(other.consensus_key()).or_default() += 1,
        }
    }
    votes.into_iter().max_by_key(|(_, n)| *n).map(|(k, _)| k)
}

/// Escape control bytes to visible text: `\r` `\n` `\t` `\0`, else `\xNN`. Keeps
/// a cell single-line and readable in both the table and the CSV.
fn escape_controls(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        match ch {
            '\r' => out.push_str("\\r"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\0' => out.push_str("\\0"),
            c if c.is_control() => {
                let _ = write!(out, "\\x{:02x}", c as u32);
            }
            c => out.push(c),
        }
    }
    out
}

/// Escape a cell for a markdown table: control bytes plus the `|` column
/// delimiter. (The CSV path uses [`escape_controls`] and lets the `csv` writer
/// handle quoting.)
fn esc(cell: &str) -> String {
    escape_controls(cell).replace('|', "\\|")
}

/// Wrap a cell in a markdown code span (the `—` placeholder stays bare), so an
/// escape like `\r` or a literal `"` reads unambiguously as monospace. A literal
/// backtick in the value would break a single-backtick span, so the fence is made
/// one backtick longer than the longest run inside, with a space pad when the
/// value abuts the fence — CommonMark's rule for backtick-bearing code spans. A
/// backtick-free value (every cell today) keeps the plain single-backtick span.
fn code(s: &str) -> String {
    if s == "—" {
        return s.to_string();
    }
    let longest_run = s.split(|c| c != '`').map(str::len).max().unwrap_or(0);
    if longest_run == 0 {
        return format!("`{s}`");
    }
    let fence = "`".repeat(longest_run + 1);
    let pad = if s.starts_with('`') || s.ends_with('`') {
        " "
    } else {
        ""
    };
    format!("{fence}{pad}{s}{pad}{fence}")
}

/// Escape raw wire bytes for display: printable ASCII verbatim, the common
/// controls as `\r`/`\n`/`\t`/`\0`, every other byte (incl. non-UTF-8) as `\xNN`.
fn escape_bytes(bytes: &[u8]) -> String {
    let mut out = String::with_capacity(bytes.len());
    for &b in bytes {
        match b {
            b'\r' => out.push_str("\\r"),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            0 => out.push_str("\\0"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                let _ = write!(out, "\\x{b:02x}");
            }
        }
    }
    out
}

/// The exact wire a scenario sends, escaped for display in full (no truncation): a
/// valid-UTF-8 wire keeps its characters (with control escapes), a non-UTF-8 wire is
/// shown byte-by-byte. Used verbatim for the HTML payload tooltip.
fn payload_full(scenario: &Scenario) -> String {
    match scenario.recipe.render_str() {
        Some(wire) => escape_controls(&wire),
        None => escape_bytes(&scenario.recipe.render()),
    }
}

/// [`payload_full`] capped to a single readable cell: a long (scale) payload
/// collapses to a head plus a length marker. The HTML report carries the full text
/// in a `title` tooltip (see [`render_html_section`]).
fn payload_of(scenario: &Scenario) -> String {
    let full = payload_full(scenario);
    let count = full.chars().count();
    if count > 36 {
        let head: String = full.chars().take(28).collect();
        format!("{head}…<{count}>")
    } else {
        full
    }
}

/// Whether a cell's outcome diverges from the real-world `consensus` — true only
/// for a *parse* outcome (not `n/a`/`SKIP`/`☠️`/a forwarding verdict) that rendered
/// differently from the modal consensus of its column. Drives the **bold** mark
/// in Markdown and the `.diverge` highlight in HTML. Shared so both renderers
/// judge divergence identically. A crash is deliberately not divergence-eligible:
/// it already stands out as `☠️`/red and never reads as a "parse disagreement".
fn diverges(outcome: &ParseOutcome, consensus: Option<&String>) -> bool {
    matches!(
        outcome,
        ParseOutcome::Cookies { .. }
            | ParseOutcome::Rejected { .. }
            | ParseOutcome::SetCookie { .. }
            | ParseOutcome::SetCookieRejected { .. }
    ) && consensus.is_some_and(|c| *c != outcome.consensus_key())
}

// ── section split ──────────────────────────────────────────────────────────────
// The matrix is split by `Direction` into two tables — the request-`Cookie:`
// parsers and the response-`Set-Cookie:` parsers — so each reads as a dense table
// instead of one wide grid where every request-only tool is `n/a` down the
// Set-Cookie columns (and vice-versa). `Expires`/date scenarios are response-only,
// so they live where they matter: in the Set-Cookie section.

/// The two section headings (backtick-quoted so HTML renders the header name as
/// `<code>` via `md_inline`; the Markdown emits them verbatim).
const REQUEST_TITLE: &str = "Request `Cookie:` parsers";
const RESPONSE_TITLE: &str = "Response `Set-Cookie:` parsers";

/// Split scenario row *indices* by direction, preserving order. Indices (not the
/// scenarios) because a section still addresses `Column.cells`, which is aligned
/// to the full scenario order.
fn partition_rows(scenarios: &[Scenario]) -> (Vec<usize>, Vec<usize>) {
    let mut request = Vec::new();
    let mut response = Vec::new();
    for (i, s) in scenarios.iter().enumerate() {
        match s.direction {
            Direction::Request => request.push(i),
            Direction::Response => response.push(i),
        }
    }
    (request, response)
}

/// Whether a column belongs in a section: it must *do something* on at least one
/// of the section's rows — parse, reject, forward, or crash. A column that is only
/// `n/a` (a parser that does not handle this direction) or only `SKIP` (a tool
/// absent from this run) is dropped, so each table lists just the parsers that
/// engage that direction. In CI every tool is present, so `n/a` cleanly marks the
/// non-directions and the split is exact.
fn column_participates(column: &Column, rows: &[usize]) -> bool {
    rows.iter().any(|&r| {
        !matches!(
            column.cells[r],
            ParseOutcome::NotApplicable | ParseOutcome::Skipped
        )
    })
}

/// Render one direction's table into the Markdown document: a `##` heading, the
/// header row (one column per test in the section), the payload/RFC/consensus
/// reference rows, then one row per participating tool. `cons` is indexed by the
/// global scenario row, so it is shared verbatim across both sections.
fn render_md_section(
    out: &mut String,
    title: &str,
    rows: &[usize],
    scenarios: &[Scenario],
    columns: &[&Column],
    cons: &[Option<String>],
) {
    let _ = write!(out, "\n## {title}\n\n");

    let mut header = String::from("| tool |");
    let mut rule = String::from("| --- |");
    for &r in rows {
        let _ = write!(header, " `{}` |", scenarios[r].id);
        rule.push_str(" --- |");
    }
    out.push_str(&header);
    out.push('\n');
    out.push_str(&rule);
    out.push('\n');

    out.push_str("| **payload** |");
    for &r in rows {
        let _ = write!(out, " {} |", code(&payload_of(&scenarios[r])));
    }
    out.push('\n');
    out.push_str("| **RFC (standard)** |");
    for &r in rows {
        let _ = write!(
            out,
            " {} |",
            esc(rfc_verdict(scenarios[r].id).unwrap_or("—"))
        );
    }
    out.push('\n');
    out.push_str("| **consensus** |");
    for &r in rows {
        let display = cons[r].clone().unwrap_or_else(|| "—".to_string());
        let _ = write!(out, " {} |", code(&esc(&display)));
    }
    out.push('\n');

    for column in columns {
        let _ = write!(out, "| {} |", column.header());
        for &r in rows {
            let outcome = &column.cells[r];
            let cell = code(&esc(&outcome.cell()));
            if diverges(outcome, cons[r].as_ref()) {
                let _ = write!(out, " **{cell}** |");
            } else {
                let _ = write!(out, " {cell} |");
            }
        }
        out.push('\n');
    }
}

/// Render one direction's table into the HTML report: an `<h2>` heading and a
/// sticky-header `.matrix-scroll` table with the same reference rows and per-tool
/// rows as [`render_md_section`]. Every untrusted cell is `h`/`hc`-escaped.
fn render_html_section(
    out: &mut String,
    title: &str,
    rows: &[usize],
    scenarios: &[Scenario],
    columns: &[&Column],
    cons: &[Option<String>],
) {
    let _ = writeln!(out, "<h2>{}</h2>", md_inline(title));
    out.push_str("<div class=\"matrix-scroll\">\n<table>\n<thead>\n<tr><th>tool</th>");
    for &r in rows {
        let _ = write!(out, "<th>{}</th>", h(scenarios[r].id));
    }
    out.push_str("</tr>\n</thead>\n<tbody>\n");

    // The cell shows the length-capped payload; the full wire rides in a `title`
    // tooltip, attribute-escaped via `ha` (never hand-rolled) so a `"` cannot escape.
    out.push_str("<tr class=\"ref\"><th>payload</th>");
    for &r in rows {
        let _ = write!(
            out,
            "<td title=\"{}\"><code>{}</code></td>",
            ha(&payload_full(&scenarios[r])),
            h(&payload_of(&scenarios[r]))
        );
    }
    out.push_str("</tr>\n<tr class=\"ref\"><th>RFC (standard)</th>");
    for &r in rows {
        let verdict = md_inline(rfc_verdict(scenarios[r].id).unwrap_or("—"));
        let _ = write!(out, "<td>{verdict}</td>");
    }
    out.push_str("</tr>\n<tr class=\"ref\"><th>consensus</th>");
    for &r in rows {
        let display = cons[r].clone().unwrap_or_else(|| "—".to_string());
        let _ = write!(out, "<td><code>{}</code></td>", hc(&display));
    }
    out.push_str("</tr>\n");

    for column in columns {
        let _ = write!(out, "<tr><th>{}</th>", h(&column.header()));
        for &r in rows {
            let outcome = &column.cells[r];
            let content = hc(&outcome.cell());
            let class = cell_class(outcome, cons[r].as_ref());
            if class.is_empty() {
                let _ = write!(out, "<td><code>{content}</code></td>");
            } else {
                let _ = write!(out, "<td class=\"{class}\"><code>{content}</code></td>");
            }
        }
        out.push_str("</tr>\n");
    }
    out.push_str("</tbody>\n</table>\n</div>\n");
}

// ── attribute fidelity ──────────────────────────────────────────────────────────
// The `resp-all-attrs` scenario sets every Set-Cookie attribute; this surfaces,
// explicitly, which parsers preserve vs silently drop each one — the information loss
// the matrix is meant to document, beyond the per-cell divergence highlight.

/// The scenario whose wire sets all six attributes (see `scenario.rs`).
const FIDELITY_SCENARIO: &str = "resp-all-attrs";
/// Those six attributes, in render order.
const FIDELITY_ATTRS: [&str; 6] = [
    "HttpOnly", "Secure", "SameSite", "Path", "Domain", "Max-Age",
];

/// Per parser, which of the six attributes it surfaced from `resp-all-attrs` (`true` =
/// kept, `false` = dropped). Only columns that parsed a cookie there are listed — one
/// that rejected it (e.g. a client jar on a domain mismatch) is omitted, not scored 0.
fn attribute_fidelity(scenarios: &[Scenario], columns: &[Column]) -> Vec<(String, [bool; 6])> {
    let Some(row) = scenarios.iter().position(|s| s.id == FIDELITY_SCENARIO) else {
        return Vec::new();
    };
    columns
        .iter()
        .filter_map(|c| match &c.cells[row] {
            ParseOutcome::SetCookie { set_cookie: sc } => Some((
                c.header(),
                [
                    sc.http_only,
                    sc.secure,
                    sc.same_site.is_some(),
                    sc.path.is_some(),
                    sc.domain.is_some(),
                    sc.max_age.is_some(),
                ],
            )),
            _ => None,
        })
        .collect()
}

/// The authored note under the fidelity table (inline Markdown, shared by both renderers).
const FIDELITY_NOTE: &str =
    "`resp-all-attrs` sets all six attributes; this is which each parser surfaces. `✗` = dropped \
     — except the client jars' `Max-Age`, which they fold into an absolute expiry rather than \
     report as such. Parsers that rejected the cookie outright are omitted.";

/// Render the attribute-fidelity grid as Markdown (a `parser × attribute` table of ✓/✗).
fn render_fidelity_md(out: &mut String, rows: &[(String, [bool; 6])]) {
    if rows.is_empty() {
        return;
    }
    let _ = write!(out, "\n## Attribute fidelity\n\n{FIDELITY_NOTE}\n\n");
    let mut header = String::from("| parser |");
    let mut rule = String::from("| --- |");
    for a in FIDELITY_ATTRS {
        let _ = write!(header, " {a} |");
        rule.push_str(" --- |");
    }
    out.push_str(&header);
    out.push('\n');
    out.push_str(&rule);
    out.push('\n');
    for (parser, present) in rows {
        let _ = write!(out, "| {parser} |");
        for &p in present {
            let _ = write!(out, " {} |", if p { "✓" } else { "✗" });
        }
        out.push('\n');
    }
}

/// Render the attribute-fidelity grid as HTML (✗ tinted via the `reject` class).
fn render_fidelity_html(out: &mut String, rows: &[(String, [bool; 6])]) {
    if rows.is_empty() {
        return;
    }
    out.push_str("<h2>Attribute fidelity</h2>\n");
    let _ = writeln!(out, "<p class=\"prose\">{}</p>", md_inline(FIDELITY_NOTE));
    out.push_str("<div class=\"matrix-scroll\">\n<table>\n<thead>\n<tr><th>parser</th>");
    for a in FIDELITY_ATTRS {
        let _ = write!(out, "<th>{a}</th>");
    }
    out.push_str("</tr>\n</thead>\n<tbody>\n");
    for (parser, present) in rows {
        let _ = write!(out, "<tr><th>{}</th>", h(parser));
        for &p in present {
            if p {
                out.push_str("<td>✓</td>");
            } else {
                out.push_str("<td class=\"reject\">✗</td>");
            }
        }
        out.push_str("</tr>\n");
    }
    out.push_str("</tbody>\n</table>\n</div>\n");
}

/// Render the whole matrix as a markdown document. `versions` is the
/// "tested against" footer — the exact comparator versions of this run.
pub fn render(scenarios: &[Scenario], columns: &[Column], versions: &[String]) -> String {
    let mut out = String::new();
    let _ = write!(out, "# {TITLE}\n\n");
    let _ = write!(out, "{INTRO}\n\n");

    // ── legend: a symbol/meaning table ────────────────────────────────────────
    out.push_str("## Legend\n\n| symbol | meaning |\n| --- | --- |\n");
    for (sym, meaning) in LEGEND_ROWS {
        let _ = writeln!(out, "| {} | {} |", code(sym), meaning);
    }
    let _ = write!(out, "\n{LEGEND_NOTE}\n\n");

    for para in NARRATIVE {
        let _ = write!(out, "{para}\n\n");
    }

    // The consensus per test, computed once over every column (n/a, SKIP and
    // crashes already abstain), so each section's filtered columns vote identically.
    let cons: Vec<Option<String>> = (0..scenarios.len())
        .map(|row| consensus(row, columns))
        .collect();

    // Two tables, split by direction; each lists only the columns that engage it.
    let (req_rows, resp_rows) = partition_rows(scenarios);
    for (title, rows) in [(REQUEST_TITLE, &req_rows), (RESPONSE_TITLE, &resp_rows)] {
        let cols: Vec<&Column> = columns
            .iter()
            .filter(|c| column_participates(c, rows))
            .collect();
        render_md_section(&mut out, title, rows, scenarios, &cols, &cons);
    }

    // ── attribute fidelity: who drops which Set-Cookie attribute ──────────────
    render_fidelity_md(&mut out, &attribute_fidelity(scenarios, columns));

    // ── prose: divergences worth knowing ──────────────────────────────────────
    out.push_str("\n## Divergences worth knowing\n\n");
    for (row, scenario) in scenarios.iter().enumerate() {
        let con = match &cons[row] {
            Some(c) => c.clone(),
            None => continue,
        };
        let subjects: Vec<&Column> = columns.iter().filter(|c| c.is_subject()).collect();
        let kekse_diverges = subjects.iter().any(|c| c.cells[row].consensus_key() != con);
        let rfc_note = rfc_verdict(scenario.id);
        if kekse_diverges {
            let modes: Vec<String> = subjects
                .iter()
                .map(|c| format!("{} → `{}`", c.dep, esc(&c.cells[row].cell())))
                .collect();
            let _ = write!(
                out,
                "- **`{}`** — {}. Real-world consensus `{}`; {}.",
                scenario.id,
                scenario.description,
                esc(&con),
                modes.join(", ")
            );
            if let Some(rfc) = rfc_note {
                let _ = write!(out, " RFC: {rfc}.");
            }
            out.push('\n');
        }
    }

    // ── tested against (exact versions of this run) ───────────────────────────
    // Code-span each line: a version banner is reported by an external tool, so
    // escape any `|`/control bytes and let it never introduce markup.
    out.push_str("\n## Tested against\n\n");
    for line in versions {
        let _ = writeln!(out, "- {}", code(&esc(line)));
    }

    out
}

// ── HTML report ──────────────────────────────────────────────────────────────
// `render_html` builds a self-contained page. Every string that originates from a
// parsed (corrupted) cookie is routed through `h`/`hc`, so it lands as inert text.
// The rule: *whoever emits the final HTML escapes* — here that is us, unlike the
// Markdown path, where the downstream renderer escapes the code spans for us.

/// HTML-escape untrusted text for *element content*: encodes `&`, `<`, `>` so the
/// value renders as text and can never start a tag or an entity. The escape
/// choke-point for text that lands in `<td>`/`<code>`. Text bound for an *attribute*
/// (the payload `title` tooltip) must use [`ha`] instead, which also escapes `"`.
fn h(s: &str) -> Cow<'_, str> {
    html_escape::encode_text(s)
}

/// HTML-escape untrusted text for a *double-quoted attribute* (the payload `title`
/// tooltip). Uses `html_escape` — never hand-rolled — so a `"` (or `&`/`<`/`>`) in a
/// payload is encoded and cannot break out of the attribute.
fn ha(s: &str) -> Cow<'_, str> {
    html_escape::encode_double_quoted_attribute(s)
}

/// Escape a *cell* display string for HTML: control bytes made visible first (the
/// HTML analogue of `esc`, which instead escapes the Markdown `|`), then HTML
/// entities encoded. `cell()`/consensus strings are raw parser output, so they
/// need the control-byte visualization the Markdown path gets from `esc`.
fn hc(s: &str) -> String {
    h(&escape_controls(s)).into_owned()
}

/// Render a span of *authored* inline Markdown to safe HTML: backtick code spans
/// become `<code>…</code>`, `**bold**`/`*italic*` become `<strong>`/`<em>`, and
/// every literal run is `h`-escaped. Not a general Markdown engine — it covers
/// only the inline features the report's prose uses, on trusted input.
fn md_inline(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 16);
    // Backticks delimit code spans: split on them, the odd segments are the spans.
    for (i, seg) in s.split('`').enumerate() {
        if i % 2 == 1 {
            let _ = write!(out, "<code>{}</code>", h(seg));
        } else {
            out.push_str(&md_emphasis(seg));
        }
    }
    out
}

/// `h`-escape a non-code run, then turn `**bold**`/`*italic*` into `<strong>`/
/// `<em>` (bold first, so its `**` is consumed before single-`*` italics).
fn md_emphasis(text: &str) -> String {
    let escaped = h(text);
    let bold = toggle_wrap(&escaped, "**", "<strong>", "</strong>");
    toggle_wrap(&bold, "*", "<em>", "</em>")
}

/// Replace each occurrence of `marker`, alternately, with `open` then `close` —
/// turning balanced marker pairs into open/close tags. Authored prose only, so
/// markers are assumed balanced and non-nested.
fn toggle_wrap(s: &str, marker: &str, open: &str, close: &str) -> String {
    let mut out = String::with_capacity(s.len());
    let mut opened = false;
    let mut rest = s;
    while let Some(pos) = rest.find(marker) {
        out.push_str(&rest[..pos]);
        out.push_str(if opened { close } else { open });
        opened = !opened;
        rest = &rest[pos + marker.len()..];
    }
    out.push_str(rest);
    out
}

/// The CSS class for a data cell: divergence (the key signal) wins; otherwise a
/// muted class for the non-parse outcomes (`n/a`/`SKIP`), a tint for rejections,
/// and an emphatic `crash` class for `☠️` (panic / sidecar death). Empty string =
/// no class.
fn cell_class(outcome: &ParseOutcome, consensus: Option<&String>) -> &'static str {
    if diverges(outcome, consensus) {
        return "diverge";
    }
    match outcome {
        ParseOutcome::NotApplicable | ParseOutcome::Skipped => "muted",
        ParseOutcome::Rejected { .. }
        | ParseOutcome::SetCookieRejected { .. }
        | ParseOutcome::ForwardedRejected => "reject",
        ParseOutcome::Panicked { .. } | ParseOutcome::Crashed { .. } => "crash",
        _ => "",
    }
}

/// Render the whole matrix as a self-contained HTML report — the GitHub Pages
/// view of the matrix. Same data and divergence logic as [`render`], but every
/// untrusted cell is entity-encoded (`h`/`hc`) and the wide table gets a sticky
/// header row and sticky first column so a tool/test stays identifiable across
/// ~60 columns. `versions` is the "tested against" footer.
pub fn render_html(scenarios: &[Scenario], columns: &[Column], versions: &[String]) -> String {
    // The consensus per test, computed once — the vote each tool row is judged
    // against, exactly as in `render`.
    let cons: Vec<Option<String>> = (0..scenarios.len())
        .map(|row| consensus(row, columns))
        .collect();

    let mut out = String::new();
    out.push_str(
        "<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n",
    );
    let _ = writeln!(out, "<title>{}</title>", h(TITLE));
    out.push_str("<style>\n");
    out.push_str(CSS);
    out.push_str("\n</style>\n</head>\n<body>\n");

    // ── header band ──────────────────────────────────────────────────────────
    let _ = writeln!(out, "<h1>{}</h1>", h(TITLE));
    let _ = writeln!(out, "<p class=\"intro\">{}</p>", md_inline(INTRO));
    out.push_str(
        "<p class=\"downloads\">Download the same matrix: \
         <a href=\"COOKIE_MATRIX.md\">Markdown</a> · \
         <a href=\"COOKIE_MATRIX.csv\">CSV</a></p>\n",
    );
    // ── legend: a symbol/meaning table ────────────────────────────────────────
    out.push_str(
        "<h2>Legend</h2>\n<table class=\"legend-table\">\n\
         <thead><tr><th>symbol</th><th>meaning</th></tr></thead>\n<tbody>\n",
    );
    for (sym, meaning) in LEGEND_ROWS {
        let _ = writeln!(
            out,
            "<tr><td><code>{}</code></td><td>{}</td></tr>",
            hc(sym),
            md_inline(meaning)
        );
    }
    out.push_str("</tbody>\n</table>\n");
    let _ = writeln!(out, "<p class=\"prose\">{}</p>", md_inline(LEGEND_NOTE));
    for para in NARRATIVE {
        let _ = writeln!(out, "<p class=\"prose\">{}</p>", md_inline(para));
    }

    // ── two tables, split by direction (rows are tools, columns are tests) ────
    let (req_rows, resp_rows) = partition_rows(scenarios);
    for (title, rows) in [(REQUEST_TITLE, &req_rows), (RESPONSE_TITLE, &resp_rows)] {
        let cols: Vec<&Column> = columns
            .iter()
            .filter(|c| column_participates(c, rows))
            .collect();
        render_html_section(&mut out, title, rows, scenarios, &cols, &cons);
    }

    // ── attribute fidelity: who drops which Set-Cookie attribute ──────────────
    render_fidelity_html(&mut out, &attribute_fidelity(scenarios, columns));

    // ── divergences worth knowing ────────────────────────────────────────────
    out.push_str("<h2>Divergences worth knowing</h2>\n<ul>\n");
    for (row, scenario) in scenarios.iter().enumerate() {
        let con = match &cons[row] {
            Some(c) => c.clone(),
            None => continue,
        };
        let subjects: Vec<&Column> = columns.iter().filter(|c| c.is_subject()).collect();
        if !subjects.iter().any(|c| c.cells[row].consensus_key() != con) {
            continue;
        }
        let modes: Vec<String> = subjects
            .iter()
            .map(|c| format!("{} → <code>{}</code>", h(&c.dep), hc(&c.cells[row].cell())))
            .collect();
        let _ = write!(
            out,
            "<li><strong><code>{}</code></strong> — {}. Real-world consensus <code>{}</code>; {}.",
            h(scenario.id),
            h(scenario.description),
            hc(&con),
            modes.join(", ")
        );
        if let Some(rfc) = rfc_verdict(scenario.id) {
            let _ = write!(out, " RFC: {}.", md_inline(rfc));
        }
        out.push_str("</li>\n");
    }
    out.push_str("</ul>\n");

    // ── tested against (exact versions of this run) ──────────────────────────
    out.push_str("<h2>Tested against</h2>\n<ul>\n");
    for line in versions {
        let _ = writeln!(out, "<li><code>{}</code></li>", h(line));
    }
    out.push_str("</ul>\n</body>\n</html>\n");

    out
}

/// Render the matrix **transposed** — one row per tool/library, one column per
/// test — as CSV, the orientation that makes a single tool's behaviour scan as a
/// row. Two blocks, split by direction (a `== … ==` banner separates them); within
/// each, `payload`/`RFC`/`consensus` lead as reference rows. The `csv` writer owns
/// quoting and escaping; cells only need control bytes made visible first. The
/// blocks have different widths, so the writer is `flexible`.
pub fn render_csv(scenarios: &[Scenario], columns: &[Column]) -> String {
    let cons: Vec<Option<String>> = (0..scenarios.len())
        .map(|row| consensus(row, columns))
        .collect();
    let (req_rows, resp_rows) = partition_rows(scenarios);

    let mut writer = csv::WriterBuilder::new()
        .flexible(true)
        .from_writer(Vec::new());
    {
        let mut record = |label: &str, cells: Vec<String>| {
            let mut row = Vec::with_capacity(cells.len() + 1);
            row.push(label.to_string());
            row.extend(cells);
            writer
                .write_record(&row)
                .expect("writing CSV to an in-memory buffer cannot fail");
        };
        for (label, rows) in [
            ("Request Cookie:", &req_rows),
            ("Response Set-Cookie:", &resp_rows),
        ] {
            let cols: Vec<&Column> = columns
                .iter()
                .filter(|c| column_participates(c, rows))
                .collect();
            record(&format!("== {label} parsers =="), Vec::new());
            record(
                "tool",
                rows.iter().map(|&r| scenarios[r].id.to_string()).collect(),
            );
            record(
                "payload",
                rows.iter().map(|&r| payload_of(&scenarios[r])).collect(),
            );
            record(
                "RFC (standard)",
                rows.iter()
                    .map(|&r| rfc_verdict(scenarios[r].id).unwrap_or("—").to_string())
                    .collect(),
            );
            record(
                "consensus",
                rows.iter()
                    .map(|&r| escape_controls(&cons[r].clone().unwrap_or_else(|| "—".to_string())))
                    .collect(),
            );
            for column in &cols {
                record(
                    &column.header(),
                    rows.iter()
                        .map(|&r| escape_controls(&column.cells[r].cell()))
                        .collect(),
                );
            }
            record("", Vec::new());
        }
    }
    let bytes = writer
        .into_inner()
        .expect("flushing the in-memory CSV buffer cannot fail");
    String::from_utf8(bytes).expect("CSV output is valid UTF-8")
}
